---
title: Jekyll
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  peoples:
    title: peoples
    output: true
    Team: Product
    Title: Software Engineer for Good
theme: jekyll-theme-architect
prose:
  siteurl: https://www.globalgiving.org
